name: woofme
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.0.4
  image_picker: ^0.8.4+5
  http: ^0.13.4

  cupertino_icons: ^1.0.2

  persistent_bottom_nav_bar: any

  flutter_profile_picture: ^2.0.0
  swipe_cards: ^2.0.0+1
  appinio_swiper: ^2.0.2
  firebase_auth: ^4.7.1
  email_validator: ^2.0.1
  url_launcher: ^6.0.10
  path: ^1.8.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/profile.png"
  min_sdk_android: 19
  background_color: "#FFFFFF"

  web:
    generate: true
    image_path: "assets/images/profile.png"
    background_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/profile.png"
  macos:
    generate: true
    image_path: "assets/images/profile.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - 'assets/images/profile.png'
    - 'assets/images/login_dog.gif'
    - 'assets/images/pup1.jpg'
    - 'assets/images/pup2.jpg'
    - 'assets/images/pup3.jpg'
    - 'assets/images/pup4.jpg'
    - 'assets/images/puppaw.png'


